source 'https://rubygems.org'

gem 'jekyll', '~> 4'
gem 'jekyll-feed'
gem 'jekyll-paginate-v2'
gem 'jekyll-responsive-image'
gem 'jekyll-sitemap'
gem 'kramdown-parser-gfm'
gem 'mini_magick'
gem 'debug'
gem 'rouge'
gem 's3_website_revived'
gem 'uglifier'
gem 'webrick'
