source 'https://rubygems.org'

gem 'jekyll', '~> 3.0.0.pre.beta8'
gem 'kramdown'
gem 's3_website'
gem 'mini_magick'
gem 'jekyll-assets'
gem 'jekyll-paginate'
gem 'pry-byebug'
gem 'jekyll-sitemap'
gem 'uglifier'
gem 'rouge'
# gem 'octopress-minify-html'
