source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-paginate'
gem 'jekyll-responsive_image'
gem 'jekyll-sitemap'
gem 'kramdown'
gem 'mini_magick'
gem 'pry-byebug'
gem 'rouge'
gem 's3_website'
gem 'uglifier'
